### ISSUE TITLE
Use virtualenvs

### ISSUE THREAD

**Issue by GaretJax** [twisted-infra/braid#1]
(just keeping track of things to discuss over here)

Virtual environments should probably still be preferred to user local installations as they provide more isolation from the system site-packages, allow to run different versions of python and don't require scripts to be invoked by specifiying the correct interpreter.

We could also activate the correct environment in each user's .profile in order to have it available for each command.

**Comment by hawkowl** [comment]
I'm doing this in prep for the Git migration plan.

**Comment by hawkowl** [comment]
See https://github.com/twisted-infra/braid/pull/189

**Comment by hawkowl** [comment]
This is Done(tm)
