### ISSUE TITLE
Remove usage of diffresource 

### ISSUE THREAD

**Issue by adiroiban** [twisted-infra/braid#102]
I would like to remove diffresource usage from Twisted infra rather then move the submodule to a folder.

I tried to applied the state on Vagrant VM  and I was able to start it ... but the documentation is not complete and I don't know how to use the started PB unix socket.

It is based on SVN. Once git migration is done, we can still use it with a SVN mirror.

It is not critical to remove diffresource.

Similar result can be obtained from github by appending .diff to the compare or PR URL.

https://github.com/twisted/twisted/compare/trunk...irc-tags-6667-4.diff

With PR urls you can get diffs for branches which were removed  or PR which were closed.

ex 
https://patch-diff.githubusercontent.com/raw/twisted-infra/braid/pull/89
https://patch-diff.githubusercontent.com/raw/twisted-infra/braid/pull/89.diff

With diffresource I can not get the diff for a closed ticket ex https://twistedmatrix.com/~diffresource.twistd/7906

**Comment by tomprince** [comment]
> https://bitbucket.org/pypa/pypi/src/4272c77983e871ff2b0152841758fcda90919d46/requirements.txt?at=default

It uses twisted.web.distrib. You can access it via t-web.

**Comment by glyph** [comment]
> It is based on SVN. Once git migration is done, we can still use it with a SVN mirror.

Once the git migration is done, let's please not have an SVN mirror.  Git can produce these diffs much faster natively.

**Comment by adiroiban** [comment]
#136 was merged... @tomprince or @hawkowl can we have it deployed ? 

I have updated the repo description for https://github.com/twisted-infra/diffresource just to have this change documented for now.

Thanks!

**Comment by adiroiban** [comment]
It was deployed. Thanks!

You can see it in action here https://twistedmatrix.com/trac/ticket/8025
