### ISSUE TITLE
use database-backed password storage instead of file-backed

### ISSUE THREAD

**Issue by adiroiban** [twisted-infra/braid#120]
https://github.com/twisted-infra/trac-config/issues/24

glyph commented on 10 Jun

https://trac-hacks.org/wiki/AccountManagerPlugin says we can keep password data in the trac database rather than in a text file.  Given that we keep having this problem where our htaccess file gets overwritten, it would be great to just not have an htaccess file at all.

specifically, see https://trac-hacks.org/wiki/CookBook/AccountManagerPluginConfiguration#SessionStore

**Comment by hawkowl** [comment]
Also fixed via https://github.com/twisted-infra/braid/pull/192!
