### ISSUE TITLE
use HTML-form-based authentication

### ISSUE THREAD

**Issue by adiroiban** [twisted-infra/braid#121]
https://github.com/twisted-infra/trac-config/issues/23

glyph commented on 10 Jun

We're currently using HTTP basic auth, which is terrible for a bunch of reasons, one of them being that browsers make "logout" challenging, and another is that password managers don't work well with them. I think we can just get rid of TwistedAuthenticator entirely when we do that.

**Comment by hawkowl** [comment]
Fixed via https://github.com/twisted-infra/braid/pull/192!
