### ISSUE TITLE
Migrate / clean Launchpad twisted-trac-integration project

### ISSUE THREAD

**Issue by adiroiban** [twisted-infra/braid#122]
https://github.com/twisted-infra/trac-config/issues/22

From https://github.com/twisted-infra/trac-config/issues/14#issuecomment-73381438

```
Already in the plan: https://bugs.launchpad.net/twisted-trac-integration/+bug/1312424

https://github.com/termie/lp2gh is a good place to start.
```

Also see:  https://github.com/twisted-infra/trac-config/issues/14#issuecomment-73400890

```
The most of the stuff remaining in twisted-trac-integration probably doesn't actually want to be in trac-config (except maybe the weekly bug report script). That repo has/had a bunch of stuff, some which has already been migrated (and I think that everything that has has been deleted. It still contains the svn-hooks, for example.
```

Here is the root content

* svn-hooks - I have no idea what they are
* tools - not related to Trac, but rather source control servers
* trac-graphs - do we still use Munin?
* trac-hooks - looks like they were already migrated
* trac-tools - I think they can be merged here

tomprince commented on 8 Feb
> svn-hooks - I have no idea what they are
These are the hooks in the main SVN repository for twisted.

**Comment by adiroiban** [comment]
this might be a duplicate of #56

**Comment by glyph** [comment]
> this might be a duplicate of #56

yep
