### ISSUE TITLE
Migrate highscores to Git

### ISSUE THREAD

**Issue by adiroiban** [twisted-infra/braid#134]
and maybe also deploy it using braid + create a staging env

**Comment by tomprince** [comment]
It is already in git and using braid. The repository just isn't currently public.

**Comment by tomprince** [comment]
It isn't currently opensource.

**Comment by adiroiban** [comment]
Is this documented somewhere in a public place?

Can we make it public, at least the documentation?

Thanks!

**Comment by adiroiban** [comment]
Here are a few things which might be documented:

* location of the private repo
* who has access to the private repo
* who has access to deploy changes
Hopefully all other things are documented inside the repo or the fabfile.

Thanks!

**Comment by rodrigc** [comment]
If highscores is not Open Source, and it is not maintained, then I suggest that
it be removed from the twistedmatrix.com web site.

**Comment by adiroiban** [comment]
I have Glyph's word (over IRC) that we will take care of this migration once we are on git... so this should not be  a problem... I trust Glyph's words :)

**Comment by adiroiban** [comment]
and twistedmatrix is close souce since it was developed by Glyph while sitting in an Apple office and by default Apple's code is not open source... even if it is a 400 lines of code

**Comment by rodrigc** [comment]
Well I don't believe anything that I can't see, but if you believe it, that's fine.

**Comment by adiroiban** [comment]
:)

**Comment by tomprince** [comment]
Highscore doesn't actually talk to svn, just track (from just having looked at the code).
