### ISSUE TITLE
Migrate IRC commit notifications to git

### ISSUE THREAD

**Issue by adiroiban** [twisted-infra/braid#137]
As a start we can use GitHub's IRC Service hooks.

We already have commit notifications for the Braid repo.

Someone with admin permission for twisted/twisted can enable them, similar to braid.

The channel should also be configured to allow sending messages without join.

**Comment by hawkowl** [comment]
@glyph can you configure the message-without-join? it's `/msg ChanServ set #CHANNELNAME mlock -nc` apparently.

**Comment by hawkowl** [comment]
It works other than that (just with an extra join/exit), so, going to close this.

**Comment by glyph** [comment]
I can't figure out how to enable it just for the bot.  And I definitely don't want to enable it for general participation, that sounds like an invitation to unblockable spam.
