### ISSUE TITLE
Migrate Trac PB svn hooks to git

### ISSUE THREAD

**Issue by adiroiban** [twisted-infra/braid#138]
Right now, they are implemented as SVN hooks.

We can translate them into git hooks.

**Comment by hawkowl** [comment]
I don't think this is required -- the PB hooks are generated by Trac, and Trac used to get notified by a post-commit script -- but trac-github does the post-commit webhook, meaning that this should just work.

**Comment by adiroiban** [comment]
Can we test that this work? 

Some of these tickets are just checklist items to make sure that all is ok in the testing environment.

Thanks!

**Comment by rodrigc** [comment]
If I look in http://twistedmatrix.com/trac/timeline
the changeset links directly to GitHub.  So good enough, I think!
