### ISSUE TITLE
Manage git mirror repo used by Trac using braid

### ISSUE THREAD

**Issue by adiroiban** [twisted-infra/braid#139]
* set up a dedicate account
* set up public keys for committers
* install the hooks
* document how new commiters are added
* document who has permisison to apply the changes to production

**Comment by adiroiban** [comment]
the main repo will be on GitHub ... but we still need a local mirror to be used by trac :( ...at least for the initial migration

**Comment by hawkowl** [comment]
Yeah, you need a local mirror. It's done in the Trac fabfile now, though.

**Comment by adiroiban** [comment]
Can you link to documentation and commit in which this was fixed?

Thanks!
