### ISSUE TITLE
Trac isn't showing keyword changes

### ISSUE THREAD

**Issue by hawkowl** [twisted-infra/braid#140]
When you change the keyword on tickets, it doesn't show up, and is hidden.

**Comment by glyph** [comment]
When did this change? It seems like a pretty serious regression, since we can't tell who reviewers are for a ticket now.

**Comment by hawkowl** [comment]
The reason I didnt notice it originally is that if you start writing a comment, it shows them. No idea why it doesn't always. I'll fix the CSS.

**Comment by glyph** [comment]
It looked to me in the document source that the problem is the template, not the CSS. Is it just a CSS rule somewhere?

**Comment by hawkowl** [comment]
yeah it seems that it's by design that it does that (what???), but I can override it in the CSS.

**Comment by glyph** [comment]
I think the design is that there's supposed to be a button to toggle it, but our shell template is based on too old of a version to have said button.

**Comment by hawkowl** [comment]
hmm. The trac template has needed a bunch of hacks for 1.0 compat, so this is just another it seems :/

**Comment by hawkowl** [comment]
Fixed in https://github.com/twisted-infra/braid/commit/341908f97d57fa4b1087e594db56a9c6fc98c229 , tested on my local dornkirk-staging, pushed to production.
