### ISSUE TITLE
Create a webhook for GitHub that will kick off buildbot runs for Twisted master

### ISSUE THREAD

**Issue by adiroiban** [twisted-infra/braid#141]
Trigger supported builders on buildbot post-commit on master

(23:49:55) glyph: adiroiban: we need it set up so that when you push to master, the buildbots do a build of master

```
# the Twisted buildbot currently uses the contrib/svn_buildbot.py script.
# This makes a TCP connection to the ChangeMaster service to push Changes
# into the build master. The script is invoked by
# /svn/Twisted/hooks/post-commit, so it will only be run for things inside
# the Twisted repository. However, the standard SVN practice is to put the
# actual trunk in a subdirectory named "trunk/" (to leave room for
# "branches/" and "tags/"). We want to only pay attention to the trunk, so
# we use "trunk" as a prefix for the ChangeSource. This also strips off that
# prefix, so that the Builders all see sensible pathnames (which means they
# can do things like ignore the sandbox properly).
```

**Comment by hawkowl** [comment]
For the GitHub migration, this will be a webhook poked by GitHub, rather than a Git hook.

**Comment by hawkowl** [comment]
GitHub pokes it with https://github.com/twisted-infra/braid/blob/trac-github/services/buildbot/master/master.cfg#L733 -- but doesn't trigger any builds yet.

**Comment by hawkowl** [comment]
In the upgrade branch, it triggers builds with the scheduler when changes happen on the master branch.
