### ISSUE TITLE
Create a builder to report mergeability status and act as pre-commit hook

### ISSUE THREAD

**Issue by adiroiban** [twisted-infra/braid#147]
Status should be sent to github

For the start, the mergeability status should only check
- svn pre-commit hook checks - topfiles
- pyflakes 

The status  should be sent by a dedicated builder

**Comment by hawkowl** [comment]
Buildbot Eight does have a GitHub status hook, need to investigate.

**Comment by adiroiban** [comment]
I can help with configuring buildbot to send commit status back to GitHub.

let me know if you need help

You can either

1. send one commit status for each builder, and you will end up with tens of statuses for a commit.
2. you can create a meta - trigger builder which triggers all the supported builder and pushes a single status once all are executed.

For my project I am using 2

**Comment by tomprince** [comment]
Github is fairly good about showing only the relevant (failing, typically) statuses. I find having individual links nicer:
- it the presence of rebuilds, it gives you a better view of the most recent status.
- it is easier to jump to the details of a failed build
- It makes partial feedback visible immediately.

**Comment by rodrigc** [comment]
How about enabling travis-ci?  It's easy to do and consumes no buildbot resources

**Comment by adiroiban** [comment]
Travis CI only runs on Ubuntu... it does not cover all the systems supported by Twisted.... osx, windows, bsd

**Comment by hawkowl** [comment]
We can have both; a screening service (Travis CI) for people when they submit PRs to catch simple problems, and our buildbots which need to run before the merge.

**Comment by rodrigc** [comment]
Sounds good

**Comment by rodrigc** [comment]
@hawkowl did you enable Travis?

**Comment by adiroiban** [comment]
I tried to create the Travis builder some years ago ... but there was not much will at that time

https://travis-ci.org/chevah/twisted/builds/23444364

https://github.com/chevah/twisted/pull/1

the was a problem with inotify tests... I think due to the filesystem used by travis ... and that filesytem might not support inotify

----------

If someone wants to see a Travis CI builders I think that we can have Travis-CI on a fork and once all is ok to propose for a merge.

Right now I no longer have time.

**Comment by hawkowl** [comment]
I believe the inotify tests got fixed when I moved my buildbots to Docker; I'll push forward on that ticket. Shouldn't be much to do now, I think...
On 21 May 2016 15:35, Adi Roiban <notifications@github.com> wrote:I tried to create the Travis builder some years ago ... but there was not much will at that time

https://travis-ci.org/chevah/twisted/builds/23444364

chevah/twisted#1

the was a problem with inotify tests... I think due to the filesystem used by travis ... and that filesytem might not support inotify



If someone wants to see a Travis CI builders I think that we can have Travis-CI on a fork and once all is ok to propose for a merge.

Right now I no longer have time.

**Comment by rodrigc** [comment]
We have Travis now for pull requests.  It's not perfect, and only tests on Ubuntu, but it is quite good.
I would say it is good enough.

I would recommend closing this ticket.

**Comment by tomprince** [comment]
We eventually want buildbot reporting statuses to GitHub for pull requests.

**Comment by adiroiban** [comment]
OK. Since @tomprince is +1 on having individual I will look at enabling them.

We now have Travis-CI failures blocking a push in trunk, so we should also have buildbot status to have a complete status.

**Comment by adiroiban** [comment]
OK. So I got something,

The github status chagnes are here https://github.com/twisted-infra/braid/commit/6f812c2793697a71c83b7259f8cf2c737bf01a99

---------

This need #204 and #205 to be merged first as the commit is based on those changes.

Basically we first need to have buildmaster/buildslave working in Vagrant (204) and then to upgrade to latest Buildbot Eight (205)

**Comment by adiroiban** [comment]
Once this hit production we will see 28 build results from buildbot

**Comment by adiroiban** [comment]
Changes are waiting the review here https://github.com/twisted-infra/braid/pull/206 :)

**Comment by adiroiban** [comment]
I have merged in master and deployed the status sending changes.

We can no decide which of the builders should block a merge.

First on the list should be the `static-checkers` builder since it contains pyflakes and topfile checker.

**Comment by adiroiban** [comment]
I think that this can be closed as we have status reports
