### ISSUE TITLE
Windows builders should generate coverage

### ISSUE THREAD

**Issue by hawkowl** [twisted-infra/braid#149]
Currently Windows doesn't generate coverage reports. This kinda sucks.

**Comment by tomprince** [comment]
Probably something like https://codecov.io/ would be useful to aggregate this.

**Comment by hawkowl** [comment]
@tomprince beat ya to it :) https://codecov.io/github/twisted/twisted

But yes, having all the Windows code not dragging down our % would be nice, plus being able to look at the Py3 changes to Windows and know what's not covered would be even better...

**Comment by hawkowl** [comment]
This is done.
