### ISSUE TITLE
Use tox to run tests on buildbot builders

### ISSUE THREAD

**Issue by adiroiban** [twisted-infra/braid#151]
maybe we can test this when we also try to update #144 

we should remove as much logic from buildbot builders as possible.

in this way, user should be able to run local tests in a similar way as builders

**Comment by hawkowl** [comment]
Things we need to do this properly:
- https://twistedmatrix.com/trac/ticket/8214
- https://twistedmatrix.com/trac/ticket/7985

**Comment by hawkowl** [comment]
Also https://twistedmatrix.com/trac/ticket/8269, but 8214 is work-aroundable.

**Comment by adiroiban** [comment]
I think that this was fixed in https://twistedmatrix.com/trac/ticket/8544
