### ISSUE TITLE
Migrate SVN commit ID's to GitHub ID's

### ISSUE THREAD

**Issue by rodrigc** [twisted-infra/braid#158]
# Migrating SVN commit ID's to GitHub #

## Find out GitHub ID's for committers ##
We have about 100 comitters on code.twistedmatrix.com.   They are in the cvs-twisted group.
For each of these accounts we need to:
 - e-mail the committer
 - ask them what GitHub ID they want to use for committing to Twisted after the GitHub migration is complete

We then need to maintain a list which maps SVN login to GitHub ID.
We can maintain this list in a flat text file in the ```twisted-infra/braid``` repository.

After the migration is complete, we need to grant access to the ```twisted/twisted``` repository
to these GitHub ID's.

**Comment by rodrigc** [comment]
@adiroiban: you have the list of SVN committers since you have direct access to the repository.

At this link: https://git-scm.com/book/en/v2/Git-and-Other-Systems-Migrating-to-Git
they mention that you can get the list of comitters in a SVN repository by doing:

```
svn log --xml | grep author | sort -u |  perl -pe 's/.*&gt;(.*?)&lt;.*/$1 = /'
```

**Comment by adiroiban** [comment]
I have created #164 to migrate the accounts.

I am not sure that we should email each of those 100 contributors 

Please suggest how we should proceed

**Comment by rodrigc** [comment]
According to @hawkowl in #164 , this is mostly done.

**Comment by rodrigc** [comment]
@hawkowl @glyph Is this item essentially done?  If so, I recommend closing this issue.

**Comment by rodrigc** [comment]
I think this is working out quite well.

**Comment by glyph** [comment]
@rodrigc - yep, definitely an improvement :)
