### ISSUE TITLE
Update wiki pages to refer to GitHub, not SVN

### ISSUE THREAD

**Issue by rodrigc** [twisted-infra/braid#159]
Update all wiki documentation to change all references to getting code from Subversion, to getting code from GitHub.

and also with working with code from git: 

https://twistedmatrix.com/trac/wiki/ContinuousIntegration/DeveloperWorkflow

https://twistedmatrix.com/trac/wiki/CommitterCheckList

**Comment by rodrigc** [comment]
@mithrandi  I think you have made good progress on this item.  Are there any other places on the wiki that need to be changed?
You might want to take a pass through https://github.com/twisted-infra/braid/milestones/Migrate-to-Git and see if there are any other loose ends that need to be handled.

**Comment by mithrandi** [comment]
I'm sure there's wiki pages that I missed, unfortunately there's way too many places that talk about VCS operations, but hopefully I've gotten most of them at this point.

**Comment by rodrigc** [comment]
@mithrandi: can you remove *-b trunk* from http://twistedmatrix.com/trac/wiki/Downloads ?
By default, if you do a git clone, it checks out the default branch which is trunk.

**Comment by rodrigc** [comment]
@mithrandi @hawkowl @adiroiban @glyph Is it OK to delete this page: http://twistedmatrix.com/trac/wiki/HgContributor .  Seems pointless now.

**Comment by glyph** [comment]
@rodrigc With a wiki, there's always history that can be restored, so just go ahead and delete.  Then if you want feedback, let people know, so they can roll back.

**Comment by rodrigc** [comment]
@glyph I don't have permission to modify http://twistedmatrix.com/trac/wiki/HgContributor

**Comment by hawkowl** [comment]
@rodrigc I poked trac and gave you the permission; refresh and you should have it :)

**Comment by rodrigc** [comment]
This needs to be changed: https://twistedmatrix.com/trac/wiki/TwistedPair
I can't modify it

**Comment by rodrigc** [comment]
I took a pass through the wiki and cleaned up a bunch of sin references.
In the Twisted documentation with the source tree, I submitted this ticket: https://twistedmatrix.com/trac/ticket/8335 for this pull request: https://github.com/twisted/twisted/pull/62

**Comment by rodrigc** [comment]
Can someone edit this page,
and replace the line with "svn co" with this link: http://twistedmatrix.com/trac/wiki/Downloads#SourceCheckout

**Comment by rodrigc** [comment]
@exarkun @hawkowl @glyph @adiroiban  This documentation is wrong: http://twistedmatrix.com/trac/wiki/WindowsBuilds .  In https://github.com/twisted/twisted/commit/3c19191fb10b815801a88f19a6069a33459babc8 , things like aap  are no longer used.

Can someone give me a pointer on how Twisted is built on Windows today?  I can then update the wiki.

**Comment by glyph** [comment]
`python setup.py bdist_wheel` is pretty much it.

**Comment by rodrigc** [comment]
What compilers work or are supported?
Is winreg needed?

**Comment by adiroiban** [comment]
I have updated the ticket description with 2 wiki pages which need to be updated

**Comment by rodrigc** [comment]
I have updated the pages in the description and others on the wiki with Subversion -> Git.
If we find any others we can uplate them as we find them.
