### ISSUE TITLE
Migrate Twisted SVN accounts to GitHub twisted/twisted

### ISSUE THREAD

**Issue by adiroiban** [twisted-infra/braid#164]
the Twisted developers who are now "core committers" for SVN, will be given access to be "core committers" to https://github.com/twisted/twisted .

Committers to Twisted must have 2FA enabled, existing Twisted org members will get given access during the migration, but those that are not part of the Twisted org can be emailed with a mention that 2FA is required, and we can invite once that is set up.

I have created this ticket to track the progress of the SVN access migration to GitHub.

If you are already member of the @twisted/twisted-contributors team please make sure you have 2FA enabled in GitHub.

If you are not a member, please create a GitHub account (if you don't have one yet), enable 2FA and request to be added to the @twisted/twisted-contributors team.

It would be great if you could send a https://keybase.io/ or to mention another Twisted contributor which can validate your identity.

As commented by @rodrigc we might want to have a list with all SVN accounts and its status.

We might need to migrate SVN access after the git migration is done and this ticket being closed

**Comment by adiroiban** [comment]
I have made the @twisted/twisted-contributors team public so that it can be mentioned :)

**Comment by adiroiban** [comment]
Here is some email which can be used to announce people of the access migration.

it can be sent to the main list

right now there are about 100 svn contributors.. so I don't know if we want to send an individual email to each of those persons.

```
As part of the Git migration plan 

I have created a ticket here to track the progress of the SVN access migration to GitHub:

https://github.com/twisted-infra/braid/issues/164

If you are already member of the @twisted/twisted-contributors team please make sure you have 2FA enabled in GitHub.

If you are not a member, please create a GitHub account (if you don't have one yet), enable 2FA and request to be added to the @twisted/twisted-contributors team.

When requesting access to twisted/twisted, it would be great if you could send a https://keybase.io/ or to mention another Twisted contributor which can validate your identity.

Please either request access over IRC on #twisted-admin or leave a comment on the dedicated GitHub Issue https://github.com/twisted-infra/braid/issues/164

Leaving a comment is recommend so that the request can be done async and we have a central collaboration point for this task.

Thanks!
```

**Comment by rodrigc** [comment]
This link lists some of the Twisted developers: https://twistedmatrix.com/trac/wiki/TwistedMatrixLaboratories

**Comment by hawkowl** [comment]
I emailed all of the TM Labs people, got a few bounces (forwarded to Adi and @glyph -- maybe glyph knows up-to-date info).

**Comment by rodrigc** [comment]
Did you manage to find GitHub login ID's for all the TM Labs people?
Was @glyph able to help with the bounces?

**Comment by hawkowl** [comment]
I think I've got most of them; the responses were mostly "I don't need/want the commit bit now" so there's not much we really need to do :)

**Comment by rodrigc** [comment]
@hawkowl that's good news!

**Comment by rodrigc** [comment]
@hawkowl Since you have notified all the necessary committers, I recommend that this item be closed.

**Comment by rodrigc** [comment]
@hawkowl @glyph Is this item essentially done?  If so, I recommend closing this issue.

**Comment by hawkowl** [comment]
Yep. If people want commit, they can poke us :)
