### ISSUE TITLE
Make sure 'master' is the main dev branch

### ISSUE THREAD

**Issue by adiroiban** [twisted-infra/braid#166]
this is here more like a checklist before the final migration

**Comment by rodrigc** [comment]
@glyph @hawkowl I don't think the item described in this ticket is worth doing.  Right now if you
```
git clone https://github.com/twisted/twisted
```
the default branch which is checked out is *trunk*, not *master*.
Not every project does this, but it is completely legal.

For example the default branch for Saltstack is *develop*.

I suggest closing this ticket out, so we can focus on the last remaining Git migration issues.

**Comment by glyph** [comment]
I agree.

`@default` can be set to something.  And frankly "master" is a nonsense term that git invented: it is the _main_ _branch_, if you have ever seen a tree in you life why would you be inclined to call that "master"?

**Comment by rodrigc** [comment]
Well if you go down the path of discussing why the designers of git chose the default behavior and naming that they did,  that is entering a black hole.  :)

So I think we are in agreement to:

- leave the default branch in git as **trunk**
- close out this issue

**Comment by glyph** [comment]
> Well if you go down the path of discussing why the designers of git chose the default behavior and naming that they did, that is entering a black hole. :)

Heh. Good point :)

**Comment by glyph** [comment]
> So I think we are in agreement to:
> 
> leave the default branch in git as trunk
> close out this issue

Yes.
