### ISSUE TITLE
Create staging Trac

### ISSUE THREAD

**Issue by adiroiban** [twisted-infra/braid#167]
It should be managed by braid and available inside the vagrant vm but it should also be public.

maybe we can have

staging.twistedmatrix.com where to publish the staging infra.

we need it public so that it will be easier to test the GitHub integration and it should be easier to ask for feedback or ask other persons to test/try/check the changes.

We can not ask everyone who want to give feedback to install braid and vagrant ...etc

**Comment by hawkowl** [comment]
Done -- the changes to implement it are on my branch.

The public IP is 162.242.246.197, and the server is nicknamed Jeb, in honour of the Kerbal :)

**Comment by adiroiban** [comment]
Is there a commit or documentation associated with this?

**Comment by hawkowl** [comment]
I've added some stuff to the README.md about it. :)

**Comment by adiroiban** [comment]
hm... I still find it sparse.

For example it does not describe where is the stating system hosted, who has access to it  or how to get accees to it
