### ISSUE TITLE
In 'staging' GitHub repo add the webhook to poke the 'staging' Trac

### ISSUE THREAD

**Issue by adiroiban** [twisted-infra/braid#169]
make sure these hooks are documented somewhere... it would be great if we could install/add them via braid

**Comment by hawkowl** [comment]
We can't install it by braid without a lot of GitHub API trash, but I have added the webhook information in the Trac service readme ( https://github.com/twisted-infra/braid/tree/trac-github/services/trac ).

**Comment by adiroiban** [comment]
Can you please give the exact information for the hook ? Example: what condition should trigger that hook?

Thanks!
