### ISSUE TITLE
Create a new twisted/twisted-staging repo

### ISSUE THREAD

**Issue by adiroiban** [twisted-infra/braid#172]
Copy ``twisted/twisted`` to ``twisted/twisted-staging`` and push this 'staging' repo to GitHub, NOT under ``twisted/twisted`` but under ``twisted/twisted-staging``

it will be used as the main repo during dev... later we might keep it around for future infra related changes

**Comment by hawkowl** [comment]
Hi Adi, thanks for doing this. How did you do it in particular? Just a new repo and then a 'git push'?

**Comment by adiroiban** [comment]
Yes. Just a new repo on GitHub and then defined a new remote and pushed trunk to it.

**Comment by adiroiban** [comment]
Do we still need https://github.com/twisted/twisted-staging ? 

Can we delete it?

**Comment by hawkowl** [comment]
Yeah, we don't need it. Deleted.

**Comment by rodrigc** [comment]
Can someone update https://github.com/twisted-infra/braid/issues/163 with this item as completed?

**Comment by adiroiban** [comment]
done... but we have the milestone, which is automatically updated
