### ISSUE TITLE
Investigate GitHub's non-profit accounts for our private config repos

### ISSUE THREAD

**Issue by hawkowl** [twisted-infra/braid#177]
I think we qualify for https://github.com/nonprofit, and it could mean we can put our private config repos on GitHub, not on dornkirk (which is soon to be replaced).

cc @glyph

**Comment by glyph** [comment]
Go ahead and ask Github about it. Conservancy is the official 501(c)3 and they already have an org, https://github.com/conservancy, so I don't know what their policy is regarding fiscal sponsorships.

**Comment by hawkowl** [comment]
We now have it on twisted-infra, and I just need to do some encryption-y things to secure it further.

**Comment by glyph** [comment]
cc @mburns since we have been talking about secrets management elsewhere

**Comment by glyph** [comment]
OK just to be clear, by "have it", you mean, "we now have nonprofit status" not "we uploaded our secrets unencrypted to github" :)

**Comment by glyph** [comment]
^ @ha

**Comment by glyph** [comment]
^ @hawkowl

**Comment by hawkowl** [comment]
@glyph we have nonprofit status :)

**Comment by hawkowl** [comment]
...and I don't think I pushed them up before we had this discussion. ...maybe we should cycle some things to go with the encrypted-at-rest scheme anyway, since my laptop with them has gone international...

**Comment by glyph** [comment]
I'm working on some trust-bootstrapping/encrypted-at-rest stuff right now already, I just wanted to know how panicked I should be :).  "your laptop passed through customs once" is a pretty low level of panic for me.

**Comment by adiroiban** [comment]
I see at https://github.com/organizatiorunns/twisted-infra/settings/billing that there are unlimited private repos for Twisted Infra organization.

I think that this can be closed.

But instead of private repo it might be better to use git-secret to secure only the small part which needs to be secure
