### ISSUE TITLE
Unpin cryptography again

### ISSUE THREAD

**Issue by mithrandi** [twisted-infra/braid#188]
The cffi-crashing-on-shutdown bug is fixed upstream, and once Twisted #8189 lands we should be OpenSSL 1.0.2f compatible, so we can revert 91b937ede4cb5f5e5a8161afab0477de981b9864.

**Comment by hawkowl** [comment]
Yep, it looks good. Ran a bunch of builds on trunk, and it all works. I'll send out an email to notify everyone.
