### ISSUE TITLE
(source) links in API docs are broken

### ISSUE THREAD

**Issue by twm** [twisted-infra/braid#196]
For example, the [(source)](http://twistedmatrix.com/trac/browser/tags/releases/twisted-16.1.1/twisted/python/filepath.py#L417) at https://twistedmatrix.com/documents/current/api/twisted.python.filepath.AbstractFilePath.html#descendant.

**Comment by hawkowl** [comment]
The latest docs have the correct URL; we need some redirector for the historical ones.

**Comment by rodrigc** [comment]
This is a duplicate of https://github.com/twisted-infra/braid/issues/148

**Comment by adiroiban** [comment]
closed as duplicate of #148
