### ISSUE TITLE
☂ Use tox for all builders

### ISSUE THREAD

**Issue by adiroiban** [twisted-infra/braid#222]
In a first step for having similar CI environments between buildbot , travis and appveyor, buildbot builders should  only install deps , run tests and publish coverage using tox environments 

Once we have a tox-env we might want to run those tests on travis-ci / appveyor instead of buildbot.

The main obstacle in having "complex" builders move to travis-ci/appveyor is the lack of a simple way to publish the "artifacts" generated during a build... ex compiles apidoc/narrative docs , windows wheel

Here is the list of sub-ticktets:
- [x] have tox env for all builders https://twistedmatrix.com/trac/ticket/8544
- [x] #151 - get a simple tox based factory TwistedToxBuildFactory
- [x] #212 - no-modules
- [x] #214 - windows bdist builder TwistedToxDistPublishFactory
- [ ] TwistedDocumentationBuildFactory
- [ ] TwistedBenchmarksFactory

**Comment by rodrigc** [comment]
I think we do this now for the most part.
