### ISSUE TITLE
containerize mailman

### ISSUE THREAD

**Issue by glyph** [twisted-infra/braid#266]
This is tricky because we need enough remnants of some mail client (exim?) and some web server (hopefully twisted web running mailman's CGI scripts as our current server does) to serve mailman; then we need to reverse-proxy the main web server into it for administration.

Luckily we delegate SMTP to mailgun now, and don't need local mail delivery; all inbound mail is forwarded from mailgun to the mailing list addresses, and this container can directly take over the SMTP port on the machine.

- grab `/etc/exim4/update-exim4.conf.conf` and stick it in the image more or less as-is
- mount the `/etc/exim4/passwd.client` file as a volume to expose the existing configured SMTP client secret to the running container
- run the debian exim service and expose its port

**Comment by glyph** [comment]
Just testing the new task-list feature on github

**Comment by adiroiban** [comment]
I guess that the plan is to move to Python hosted mailing list... so we will not put any more work into this.
