### ISSUE TITLE
Install PyPy from PPA rather than binary tarball

### ISSUE THREAD

**Issue by glyph** [twisted-infra/braid#39]
Packages are nice, we should use packages.

Among other things, the current PyPy deployment situation means that we can't deploy on an i386 VM for testing.

**Comment by glyph** [comment]
@GaretJax - we should totally use virtualenv instead of `--user`. If you wanted to submit a PR with that I'd be happy to change things.

**Comment by hawkowl** [comment]
Yeah, I don't think this is a good direction. The PPA lags behind a bunch, and doesn't really give us any big benefit, I think.
