### ISSUE TITLE
switch to git on code.twistedmatrix.com as the official repository so that we can maintain merge metadata

### ISSUE THREAD

**Issue by glyph** [twisted-infra/braid#68]
I keep telling people I want to do this, and this is the place where infrastructure changes happen, so here's an issue we can start putting information on.  How are we going to do this?  What infrastructure pieces are missing?  For starters, I believe there are some subversion hooks someplace that need to be included in braid and mutated into git hook instead.

**Comment by adiroiban** [comment]
what merge metadata is is lost?

I like the current `git merge --squash` process.

Since you can not test a change on buildbot without a commit and since it hard to ask developers to locally install windows/linux/osx/bsd/py2.6/py2.7/py3.3 etc I think that is a good think to use `merge --squash`.

 When a branch is  reversed you will reverse the whole merge not only a particular commit.
 What is the benefit of having in trunk individual commits like these:

```
r44352 M(branches/tiprocess-py3-5987-3/twisted/internet/test/test_gireactor.py): don't need to reference this ...
r44353 M(branches/tiprocess-py3-5987-3/twisted/test/process_tester.py): don't need that py3 ...
r44354 branches/tiprocess-py3-5987-3/twisted M(process.py test_gireactor.py test_process.py compat.py): compat stuff ...
r44355 M(branches/tiprocess-py3-5987-3/twisted/python/compat.py): compat docs ...
r44356 M(branches/tiprocess-py3-5987-3/twisted/internet/test/test_process.py): explicit decodes ...
r44357 branches/tiprocess-py3-5987-3/twisted/internet M(base.py process.py): sorting some more things out ...
r44358 M(branches/tiprocess-py3-5987-3/twisted/internet/process.py): fix test ...
r44359 M(branches/tiprocess-py3-5987-3/twisted/test/process_tester.py): cant import twisted ...
r44360 branches/tiprocess-py3-5987-3/twisted/internet/test M(process_gireactornocompat.py test_gireactor.py): sort some things ...
r44361 M(branches/tiprocess-py3-5987-3/twisted/internet/test/test_gireactor.py): maybe this will work?? ...
```

**Comment by tomprince** [comment]
@adiroiban You can get the history you want by pass `--first-parent` to `git log`. In addition, is possible to revert a merge commit (you need to specify which parent to revert against, but for merges to trunk, that should always be the first parent.

The metadata that is lost the branch that it came from. Certainly that data is in the current merge message, but
- that requires keeping around all the old branches
- requires string parsing, rather than using native metadata
- doesn't allow using git tools to examine that history.

**Comment by adiroiban** [comment]
Thanks!

I would like to help with this and work on a fab file for setting / documenting the git server.

My plan is to set up a git service in the Vagrant VM.

---------

So the plan is to host the main Git repo on code.twistedmatrix.com wolfwood and continue to mirror it on GitHub?

------

Once main repo is moved on git the `merge --squash` will be dropped and a new git merge process will be set. Are there any info / docs for the new merge process?

Can we start with the current `merge --squash` and migrate to a new process after main repo is moved to git?

---------

I see that many other repos in /svn folder on wolfwood, are the still in use? Do they also need to be migrated to git?

What is /git/Twisted-scratch/ ? ... looks like it is used as part of the mirror process. so maybe it can be ignored  as will no longer be used once migration is done

--------

I see that hooks are part of lp:twisted-trac-integration.

The hooks are there for:
* pre-commit enforce news
* post-commit - GIT, BZR, MAILER, RSYNC, COMMITBOT, TRACBOOT, BUILDBOT

Do we still want the BZR mirror? 

Is MAILER of any use in its current form http://blog.gmane.org/gmane.comp.python.twisted.commits ? Does it need to send emails for each and every commit? 

What is the purpose of /svn/Twisted/hooks/rsync-repo ? it is a binary and does not accept the -h argument....

Thanks!

**Comment by glyph** [comment]
> On Apr 12, 2015, at 07:13, Adi Roiban <notifications@github.com> wrote:
> 
> Thanks!
> 
> I would like to help with this and work on a fab file for setting / documenting the git server.
> 
> My plan is to set up a git service in the Vagrant VM.
> 
Sounds good.
> So the plan is to host the main Git repo on code.twistedmatrix.com wolfwood and continue to mirror it on GitHub?
> 
Yes.  GitHub's user interface and workflow is really fantastic, but GitHub monoculture is still a bit of a concern for me.

The synchronization could be bi-directional, however.  Doing merges on GitHub should be fine, as long as they are mirrored on code.twistedmatrix.com <http://code.twistedmatrix.com/>.  That seems like it would be another step, though.
> Once main repo is moved on git the merge --squash will be dropped and a new git merge process will be set. Are there any info / docs for the new merge process?
> 
Same format message for the commit, just don't --squash or --fast-forward.  In other words, git merge --no-ff.
> Can we start with the current merge --squash and migrate to a new process after main repo is moved to git?
> 
That eliminates about 2/3 of the benefit of moving to git, but if you feel it would be easier to start with squash merges we could do that for a couple of days until a new document can be written explaining the new process.
> I see that many other repos in /svn folder on wolfwood, are the still in use? Do they also need to be migrated to git?
> 
Don't worry about those.  code.twistedmatrix.com <http://code.twistedmatrix.com/> will still be running.
> What is /git/Twisted-scratch/ ? ... looks like it is used as part of the mirror process. so maybe it can be ignored as will no longer be used once migration is done
> 
Yes.  I would have deleted it already except I'm not sure if it's part of some script that does the mirroring, and we don't have a good enough test environment for me to have any confidence I wouldn't be breaking something.
> I see that hooks are part of lp:twisted-trac-integration.
> 
> The hooks are there for:
> 
> pre-commit enforce news
> post-commit - GIT, BZR, MAILER, RSYNC, COMMITBOT, TRACBOOT, BUILDBOT
> Do we still want the BZR mirror?
> 
We can get rid of the bzr mirror, as soon as we don't have any buildbots that use it.  (And this needs to be done _before_ the git migration, because bzr mirroring from git is incompatible with bzr mirroring from svn.)
> Is MAILER of any use in its current form http://blog.gmane.org/gmane.comp.python.twisted.commits <http://blog.gmane.org/gmane.comp.python.twisted.commits> ? Does it need to send emails for each and every commit?
> 
Personally I don't read those messages.  I think there are still a few people who use that resource, though.
> What is the purpose of /svn/Twisted/hooks/rsync-repo ? it is a binary and does not accept the -h argument....
> 
It's a binary because only ELF binaries can be setuid, and it needs to be setuid to the "trac" user, for access to the trac SSH key.

I have no idea how the binary was generated, but I believe it's running /home/trac/rsync-server.sh, or was somehow generated from that script.

**Comment by adiroiban** [comment]
Thanks for your comments.

I am aware of the limitations of GitHub for general projects... but GitHub code browsing is fast and Pull Request are better than any Trac plugin... GitHub Issues part is a disaster.

For commit bot and mailer maybe we can use the GitHub service hooks? In this way we don't have to write/maintain our own and the GitHub servers already have a configuration GUI and should be easy to provide access to more people to manage them,

What do you think?

**Comment by glyph** [comment]
> On Apr 14, 2015, at 05:20, Adi Roiban <notifications@github.com> wrote:
> For commit bot and mailer maybe we can use the GitHub service hooks? In this way we don't have to write/maintain our own and the GitHub servers already have a configuration GUI and should be easy to provide access to more people to manage them,
> 
I think this would be fine, as long as the same functionality is available.

**Comment by adiroiban** [comment]
Just a note. GitHub pull request merge button is very simple and will merge with fast-forward.
I hope that soon GitHub will allow setting the merge method (no-ff or squash)

I will start with migrating bzr builders. This is another reason to have someone reviewing the vagrant changes.

**Comment by glyph** [comment]
Huh, I could have sworn that on other projects it was properly producing merge commits.  Where have you seen the merge button produce a fast-forward?

**Comment by adiroiban** [comment]
My bad. It does merge without fast-forward. Sorry for the noise.

I got a vagrant VM with a buildmaster and a connected builslave so it should be easy to migrate the bzr builders to git.

Any news regarding the PR I have sent to braid?

I would like to continue working an this and help Twisted-infra but is very hard to continue when I see that my changes are not reviewed.

In case the changes are junk and you don't want to waste time reviewing them, please let me know!

Thanks!

**Comment by jakesyl** [comment]
Any more updates on this?

**Comment by adiroiban** [comment]
@glyph @tomprince @hawkowl can you please review the Migrate to git milestone (https://github.com/twisted-infra/braid/milestones/Migrate%20to%20Git.)  to check that all services which needs migration have a dedicate ticket

Thanks!

**Comment by reubano** [comment]
@adiroiban wrong url above... https://github.com/twisted-infra/braid/milestones/Migrate-to-Git works

**Comment by rodrigc** [comment]
Should this item be closed out, now that the migration to github is well underway?

**Comment by glyph** [comment]
Yep, we skipped this step.
