### ISSUE TITLE
document twistedchecker dependency installation

### ISSUE THREAD

**Issue by glyph** [twisted-infra/braid#69]
It seems that the thing that provisions the twistedchecker builder doesn't install all the dependencies.  I had to install some logilab stuff manually to get things up and running again, because it wasn't clear to me where in braid that ought to go.

**Comment by adiroiban** [comment]
In case this lands https://github.com/twisted-infra/twisted-buildbot-configuration/pull/13 we will install twistedchecker using pip and this should take care of all dependencies... otherwise it is a bug in twistedchecker itself.

**Comment by adiroiban** [comment]
we now install twistedchecker with pip so all its dependencies should be defined in twistedchecker's setup.py

I think that this is closed now as we have a more 'common practice' way of installing twistedchecker and this does not need documentation
