### ISSUE TITLE
Remove logic to detect SVN revision in buildbot

### ISSUE THREAD

**Issue by tomprince** [twisted-infra/braid#73]
- [x] `txbuildbot.bzrsvn`
- [ ] `txbuildbot.git.TwistedGit`
  - branch munging (although this may want to be retained for a bit for compatibility
  - `git_revision` logic.
- Maybe other stuff.

**Comment by adiroiban** [comment]
txbuildbot.bzrsvn should be handled here https://github.com/twisted-infra/twisted-buildbot-configuration/pull/12

**Comment by adiroiban** [comment]
with the new migration plan trunk branch will be named 'master'

we need to see how to detect release branches... maybe look for tags... I don't know

**Comment by hawkowl** [comment]
I think this is all done now.

**Comment by adiroiban** [comment]
Thanks!

Do you have a commit in which this was fixed?

I think that this is about having buildbot treat relase branches as a special case ... and the logic was based on the branch name containing the 'branches' text ...
