### ISSUE TITLE
Vagrantfile

### ISSUE THREAD

**Issue by glyph** [twisted-infra/braid#75]
I'd like to be able to provision a local VM for working on the infrastructure.  A Vagrantfile would make this a lot easier.

**Comment by glyph** [comment]
#70 would help with this.

**Comment by adiroiban** [comment]
I don't have to much time for this, but I can ask the sysadmin from my project to take a look at this.

What needs to be done in order to have this ticket closed?

Does twisted infrastructure uses a single host? if not, how many? I assume we will need a vagrant file for each host.

**Comment by glyph** [comment]
Twisted's infrastructure resides on many hosts, but the "host" part of it is a lot less interesting than the "role" part.  Right now we have buildmaster + web server + postgres + trac + highscores on the same server, then SVN on a different server, then N buildslave servers in various places.  What I'd like for a Vagrantfile, though, is a host with all the roles: a buildmaster with some sample build data, a web server, a trac instance with a postgres database with some sample data in its schema...

however, to close this ticket, a Vagrantfile which provisioned any *one* of these roles would be sufficient; we can add more roles in later changes.

**Comment by tomprince** [comment]
`braid` itself should be able to do most of the provisioning, once it has a instance to connect to. To get it to talk to a different machine, put a file describing that machine in ~/.config/braid/staging.env (or the like). The big thing that is missing to make it easy for most of the roles is probably the sample data.
