### ISSUE TITLE
Move submodules into braid repo

### ISSUE THREAD

**Issue by adiroiban** [twisted-infra/braid#79]
I think that git submodules are abused here and it make it harder to work with braid for infrastructure.

submodules should be used when the same repo is used between multiple other repos but I can see that only braid uses them.. and I don't know how you can reuse them in other places.

Also, it should be much easier to follow issues and pull requests as we will have a single repo

**Comment by tomprince** [comment]
I'm not going to comment on the desirability of this change, but it probably makes sense to explain the reasoning behind the original choices.

The biggest reason for there being multiple repositories is that many of the repositories were prexisting (if you look at the history, you can see that they pre-date braid by a large amount). braid was originally envisioned as a library that was going to be used by all these separate repositories; the fact they they exists as submodules is merely a convenient way of keeping a list of all the relevant repositories handy.

**Comment by adiroiban** [comment]
Many thanks for the info.

Why not comment on the desirability of this change?

From my point of view (as an outside new contributor) braid is not a library but rather the core code which helps maintain Twisted infra. I also think that the usage of braid as a library is abused. It is ok to keep it in a separate package but not in separate repo.
Is braid used outside of Twisted-infra?

if braid is a library, why it imports other repos as submodule?
I was expecting the other way round, ie the buildbot-configuration repo to have a braid submodule.. or better, install it using pip.

I think that having a single repo will help with the maintenance of the vagrant VM and also speed up development as changes will only have to land and be reviewed in a single repo, issues and PR will be followed in a single repo.

Also, it would be much easier to create new services.
For example I want to start working on the git services, but this will require asking twisted-infra developers to create the new repo in the first place.

With current infrastructure we would either need to distribute Vagrant VM config file as port of braid library or duplicate it across all submodules.

**Comment by tomprince** [comment]
> Why not comment on the desirability of this change?

Mostly because I haven't thought about it, and am not involved in ongoing operation, and partly as the original author I am somewhat biased.

> not a library but rather the core code which helps maintain Twisted infra.

I had originally envisioned braid as a somewhat generic layer building some abstractions over fabric. Perhaps it hasn't turned out that way. Probably parts of it are that, and parts are twisted-specific.

> but this will require asking twisted-infra developers to create the new repo in the first place.

You can just create a new repo, and if we decide to add it, it can be moved into twisted-infra.

**Comment by adiroiban** [comment]
With all braid / twisted-infra code in a single repo we would not have to create 2 PR for deploying a change.

For example

https://github.com/twisted-infra/braid/pull/64
https://github.com/twisted-infra/trac-config/pull/8

**Comment by adiroiban** [comment]
buildbot was merged.

I am going to close this one and open a separate PR for each submodule.

Many thanks for your feedback!
