### ISSUE TITLE
Use upstream buildbot eight version

### ISSUE THREAD

**Issue by adiroiban** [twisted-infra/braid#81]
This issue should have been for twisted-buildbot-configuration but I can not fill tickets there.

From configuration I see that Twisted is deploying a forked Buildbot master as a full git repo https://github.com/twisted-infra/buildbot

I have this diff

It would help to have a list of problems / changes made since the fork and to document that changes

and then try to use the upstream version

**Comment by tomprince** [comment]
Looking at it there are:
- fixes backported from upstream master
- some changes to support some corner-cases that twisted's configuration that perhaps aren't appropriate upstream
- a couple of minor improvements that should be upstream.
- experimental support for forcing builds over PB (so that the status can be monitored)

**Comment by tomprince** [comment]
https://github.com/buildbot/buildbot/compare/master...twisted-infra:master

**Comment by adiroiban** [comment]
Thanks!

Since the diff is not that big I would like to try to move the corner-cases outside of buildbot code and put them into buildbot-configuration branch with the goal to make it easier to update the buildmaster.

builbot_try already support triggering builds over PB ... and if patch functionality is not desired I think that it not hard to patch buildbot not to accept patches (ex set invalid path for the patch command or drop the patch part of the request)

Is the builds forcing over PB used in other places, other than SVN hook?

**Comment by glyph** [comment]
Thanks @adiroiban ! It would be great to be running a stock buildbot so we can install updates :).

**Comment by tomprince** [comment]
I'm not sure it is actually used anywhere.

**Comment by tomprince** [comment]
I was experimenting building a tool that would wait for the results of a build.

**Comment by adiroiban** [comment]
I think that we need to update the buildbot to upstream eight branch as we would need it for github status and hooks

I saw that @hawkowl has start backporting the github hooks code, but I think that we should just update to latest eight branch.

I think that we can get rid of the PB support as I don't think that it it used.

I have pushed latest eight branch and will see what patches are still required https://github.com/buildbot/buildbot/compare/master...twisted-infra:eight-twisted-fork

**Comment by adiroiban** [comment]
Also merged in master and deployed.

db was updated.

backup data at /root/buildbot-data-2016-06-23.tar.gz
