### ISSUE TITLE
Move buildmaster private data into a private repo

### ISSUE THREAD

**Issue by adiroiban** [twisted-infra/braid#85]
Maybe we can migrate Tom's personal repo as a private repo on GitHub

In this way it should be easier to manage permissions to it.

If we can not get a private repo in Twisted-infra or Twisted organization I can donate a repo from my organization.

**Comment by hawkowl** [comment]
This is done now -- it's on `wolfwood.twistedmatrix.com:/git/buildbot-secrets`.

**Comment by adiroiban** [comment]
Do we have documentation for this new repo?

I think that the ticket description should have been. move private repo and document it :)

Thanks!
