### ISSUE TITLE
Use a released version of Twistedchecker for the twistedchecker builder

### ISSUE THREAD

**Issue by adiroiban** [twisted-infra/braid#87]
Right now it uses the trunk version without installing it.

I think that using trunk without install is wrong and if we really need this than this is a hint that twistedchecker should be part of Twisted trunk.

With the future changes in https://github.com/twisted/twistedchecker/pull/97 the build will fail as the bin/twistedchecker script is not available before install.

I suggest that we should stop running uninstalled trunk version and instead find a way automatically install the dependencies in the builder.

For example, we can use the twisted[.dev] optional dependency and have pip run as a step in the builder. For this we might need a virtualenv.

Please suggest how can we solve this problem. Thanks!

**Comment by tomprince** [comment]
IIRC, that builder was added when twistedchecker was being developed as twisted GSoC project, so changing rapidly. It also didn't have any releases, at that point. It probably makes sense to change that to use a real package now.

**Comment by adiroiban** [comment]
I have created a virtualenv based builder for twistedchecker with installs a specific version
