### ISSUE TITLE
Add builder with latest pyopenssl and openssl version

### ISSUE THREAD

**Issue by adiroiban** [twisted-infra/braid#88]
Once this patch lands https://twistedmatrix.com/trac/ticket/7860 we would need a builder for pyopenssl 0.15 and openssl 0.1.2

The builder can be dedicated to latest / bleeding edge openssl version and used for integrated Twisted with latest featured available in openssl.

Debian sid has openssl 0.1.2 package https://packages.debian.org/sid/openssl so it can be a good candidate

We can also turn this into a generic bleeding edge builder which will also have latest versions of pycrypto ... pyasn1, etc.

**Comment by hawkowl** [comment]
The tox builders now have this, + the other virtualenv builders...
